// <copyright file="ILookupRepository.cs" company="Global Mobile Software LLC">
// Copyright © 2025 All Rights Reserved
// </copyright>
// <author>Generated by OpenAI Assistant</author>
// <date>03/06/2025</date>
// <summary>Repository contract for lookup data used by rewards and rules engine authoring.</summary>

using System.Collections.Generic;

namespace GMS.TifoXRCoreWebAPI.Repositories
{
    public interface ILookupRepository
    {
        Task<IReadOnlyList<IDictionary<string, object?>>> GetRewardCompositionTypesAsync();
        Task<IReadOnlyList<IDictionary<string, object?>>> GetRewardStatusesAsync();
        Task<IReadOnlyList<IDictionary<string, object?>>> GetStateTypesAsync();
        Task<IReadOnlyList<IDictionary<string, object?>>> GetRuleActionTypesAsync();
        Task<IReadOnlyList<IDictionary<string, object?>>> GetEventTypesAsync();
        Task<IReadOnlyList<IDictionary<string, object?>>> GetComparatorsAsync();
        Task<IReadOnlyList<IDictionary<string, object?>>> GetLogicalOperatorsAsync();
        Task<IReadOnlyList<IDictionary<string, object?>>> GetPathTypesAsync();
        Task<IReadOnlyList<IDictionary<string, object?>>> GetProviderTypesAsync();
        Task<IReadOnlyList<IDictionary<string, object?>>> GetContextParametersAsync();
        Task<IReadOnlyList<IDictionary<string, object?>>> GetEventTypeParametersAsync(int eventTypeId);
    }
}
