// <copyright file="LookupController.cs" company="Global Mobile Software LLC">
// Copyright © 2025 All Rights Reserved
// </copyright>
// <author>Generated by OpenAI Assistant</author>
// <date>03/06/2025</date>
// <summary>Lookup endpoints backing the no-code authoring UI.</summary>

using System.Collections.Generic;
using GMS.TifoXRCoreWebAPI.Middleware;
using GMS.TifoXRCoreWebAPI.Middleware.Errors;
using GMS.TifoXRCoreWebAPI.Services;
using Microsoft.AspNetCore.Mvc;

namespace GMS.TifoXRCoreWebAPI.Controllers
{
    [ApiController]
    [Route("api/lookups")]
    [Produces("application/json")]
    public sealed class LookupController : ControllerBase
    {
        private readonly ILookupService _svc;
        public LookupController(ILookupService svc) => _svc = svc;

        [HttpGet("reward-composition-types")]
        public async Task<ActionResult<IReadOnlyList<IDictionary<string, object?>>>> GetRewardCompositionTypes()
            => Ok(await _svc.GetRewardCompositionTypesAsync());

        [HttpGet("reward-status")]
        public async Task<ActionResult<IReadOnlyList<IDictionary<string, object?>>>> GetRewardStatuses()
            => Ok(await _svc.GetRewardStatusesAsync());

        [HttpGet("state-types")]
        public async Task<ActionResult<IReadOnlyList<IDictionary<string, object?>>>> GetStateTypes()
            => Ok(await _svc.GetStateTypesAsync());

        [HttpGet("action-types")]
        public async Task<ActionResult<IReadOnlyList<IDictionary<string, object?>>>> GetRuleActionTypes()
            => Ok(await _svc.GetRuleActionTypesAsync());

        [HttpGet("event-types")]
        public async Task<ActionResult<IReadOnlyList<IDictionary<string, object?>>>> GetEventTypes()
            => Ok(await _svc.GetEventTypesAsync());

        [HttpGet("comparators")]
        public async Task<ActionResult<IReadOnlyList<IDictionary<string, object?>>>> GetComparators()
            => Ok(await _svc.GetComparatorsAsync());

        [HttpGet("logical-operators")]
        public async Task<ActionResult<IReadOnlyList<IDictionary<string, object?>>>> GetLogicalOperators()
            => Ok(await _svc.GetLogicalOperatorsAsync());

        [HttpGet("path-types")]
        public async Task<ActionResult<IReadOnlyList<IDictionary<string, object?>>>> GetPathTypes()
            => Ok(await _svc.GetPathTypesAsync());

        [HttpGet("provider-types")]
        public async Task<ActionResult<IReadOnlyList<IDictionary<string, object?>>>> GetProviderTypes()
            => Ok(await _svc.GetProviderTypesAsync());

        [HttpGet("context-parameters")]
        public async Task<ActionResult<IReadOnlyList<IDictionary<string, object?>>>> GetContextParameters()
            => Ok(await _svc.GetContextParametersAsync());

        [HttpGet("event-type-parameters")]
        public async Task<ActionResult<IReadOnlyList<IDictionary<string, object?>>>> GetEventTypeParameters([FromQuery] int eventTypeId)
        {
            if (eventTypeId <= 0)
                throw ErrorService.Exception(
                    ErrorType.Argument,
                    nameof(GetEventTypeParameters),
                    ErrorMessages.Validation.PositiveIntRequired,
                    paramName: nameof(eventTypeId),
                    parameters: new { eventTypeId });

            var rows = await _svc.GetEventTypeParametersAsync(eventTypeId);
            return Ok(rows);
        }
    }
}
